bkt_name := "tf-erp-state-bkt"
region := "ap-south-1"


create_tf_state_bucket:
  aws s3api create-bucket \
    --bucket {{bkt_name}} \
    --region ap-south-1 \
    --create-bucket-configuration LocationConstraint={{region}}

  aws s3api put-bucket-versioning \
    --bucket {{bkt_name}} \
    --versioning-configuration Status=Enabled \
    --region {{region}}

create_dynamodb_tf_lock:
  aws dynamodb create-table \
    --table-name tf-locks \
    --attribute-definitions AttributeName=LockID,AttributeType=S \
    --key-schema AttributeName=LockID,KeyType=HASH \
    --billing-mode PAY_PER_REQUEST \
    --region {{region}}