---
- name: Enable unattended upgrades on Debian EC2
  hosts: hosts
  become: true

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - unattended-upgrades
          - apt-listchanges
        state: present
        update_cache: yes

    - name: Enable unattended upgrades
      debconf:
        name: unattended-upgrades
        question: unattended-upgrades/enable_auto_updates
        vtype: boolean
        value: "true"

    - name: Configure unattended-upgrades allowed origins
      copy:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        content: |
          Unattended-Upgrade::Allowed-Origins {
                  "${distro_id}:${distro_codename}-security";
                  "${distro_id}:${distro_codename}-updates";
          };
          Unattended-Upgrade::Automatic-Reboot "true";
          Unattended-Upgrade::Automatic-Reboot-Time "05:00";

    - name: Configure periodic updates
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Download-Upgradeable-Packages "1";
          APT::Periodic::Unattended-Upgrade "1";

    - name: Run unattended-upgrade dry run (sanity check)
      command: unattended-upgrade --dry-run --debug
      register: dryrun_result
      changed_when: false

    - name: Show dry-run output
      debug:
        var: dryrun_result.stdout
