install_docker: 
  ansible-playbook -i inventory.ini playbook.yml -vv

update_system:
  ansible-playbook -i inventory.ini playbooks/update_system.yml -vv

install_coolify:
  ansible-playbook -i inventory.ini playbooks/install_coolify.yml -vv
